export const sampleContactData = [
  {
    id: "1",
    name: "Captain America",
    group: "a",
    phone: "0123456789",
    email: "captain.america@gmail.com",
    birthday: "1990/01/02",
    summary:
      "I'm Captain America, Steve Rogers, a super-soldier and symbol of justice, leading the fight for freedom and defending the world.",
    address: "Empire State Building, 5th Avenue, New York, NY, USA",
    photoURL: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: "2",
    name: "Batman",
    group: "a",
    phone: "0123456788",
    email: "batman@gmail.com",
    birthday: "1991/01/01",
    summary:
      "I'm Batman, also known as Bruce Wayne, a vigilante detective in Gotham City, fighting crime and injustice with my dark persona.",
    address: "Gohamcity , Punch & Judy, Henrietta Street, London, UK",
    photoURL: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: "3",
    name: "Antman",
    group: "b",
    phone: "0123456788",
    email: "antman@gmail.com",
    birthday: "1992/01/01",
    summary:
      "I'm Ant-Man, Scott Lang, a hero who shrinks to ant-size with incredible strength, aided by my trusty ants, and a member of the Avengers.",
    address: "Gohamcity , Punch & Judy, Henrietta Street, London, UK",
    photoURL: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: "4",
    name: "Deadpool",
    group: "c",
    phone: "0123456781",
    email: "deadpool@gmail.com",
    birthday: "1993/01/01",
    summary:
      "I'm Deadpool, Wade Wilson, the Merc with a Mouth, armed with sarcasm, rapid healing, and a penchant for breaking the fourth wall.",
    address: "Gohamcity , Punch & Judy, Henrietta Street, London, UK",
    photoURL: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: "5",
    name: "Superman",
    group: "d",
    phone: "0123456781",
    email: "superman@gmail.com",
    birthday: "1999/01/01",
    summary:
      "I'm Superman, also known as Clark Kent, the last son of Krypton. I protect Earth with my superhuman abilities and sense of justice.",
    address: "Gohamcity , Punch & Judy, Henrietta Street, London, UK",
    photoURL: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: "6",
    name: "Flash",
    group: "e",
    phone: "0123456781",
    email: "flash@gmail.com",
    birthday: "1994/01/01",
    summary:
      "I'm the Flash, Barry Allen, the fastest man alive, harnessing the Speed Force to protect Central City and make the impossible possible.",
    address: "Gohamcity , Punch & Judy, Henrietta Street, London, UK",
    photoURL: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: "7",
    name: "Falcon",
    group: "f",
    phone: "0123456781",
    email: "falcon@gmail.com",
    birthday: "1992/01/01",
    summary:
      "I'm Falcon, Sam Wilson, a skilled aviator and hero with a high-tech winged suit, dedicated to defending the world alongside the Avengers.",
    address: "Gohamcity , Punch & Judy, Henrietta Street, London, UK",
    photoURL: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: "8",
    name: "Black widow",
    group: "f",
    phone: "0123456781",
    email: "blackwidow@gmail.com",
    birthday: "1993/01/01",
    summary:
      "I'm Black Widow, Natasha Romanoff, a highly trained spy and expert assassin, using my skills to fight alongside the Avengers.",
    address: "Gohamcity , Punch & Judy, Henrietta Street, London, UK",
    photoURL: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: "9",
    name: "Wonder women",
    group: "f",
    phone: "0123456781",
    email: "wonder_women@gmail.com",
    birthday: "1994/01/01",
    summary:
      "I'm Wonder Woman, Diana Prince, an Amazonian warrior and champion of truth and justice, defending humanity with my superhuman abilities.",
    address: "123 Main Street, Apt 4B, New York, NY 10001, USA",
    photoURL: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: "10",
    name: "Scarlet Witch",
    group: "f",
    phone: "0123456781",
    email: "wonder_girl@gmail.com",
    birthday: "1993/01/01",
    summary:
      "I am Scarlet Witch, Wanda Maximoff. With reality-altering powers, I navigate a complex journey through magic and identity, shaping the MCU's fate with my formidable abilities.",
    address: "123 Main Street, Apt 4B, New York, NY 10001, USA",
    photoURL: "https://randomuser.me/api/portraits/women/3.jpg",
  },
];
